In [0]:
import keras

In [0]:
import numpy as np

In [0]:
data_in = np.array([[0, 0],[0, 1],[1,0],[1, 1]])

In [5]:
data_in

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [0]:
logic_and = np.array([[0], [0], [0], [1]])
logic_or = np.array([[0], [1], [1], [1]])
logic_xor = np.array([[0], [1], [1], [0]])

In [0]:
model = keras.models.Sequential(layers = [
    keras.layers.Dense(input_dim=2, units=2),
    keras.layers.Activation(keras.activations.sigmoid),
    keras.layers.Dense(units=1),
    keras.layers.Activation(keras.activations.sigmoid)
])
model.compile(optimizer=keras.optimizers.SGD(lr=0.5), loss='binary_crossentropy')

In [72]:
keras.backend.eval(model.weights[1])

array([-1.6949478, -6.3802495], dtype=float32)

In [73]:
 model.fit(data_in, logic_xor, epochs=10000, verbose=False)
  

In [75]:
model.predict(np.array([[0,1]]))

array([[0.9986829]], dtype=float32)